extends Node
## GENERATED by pipeline/gen_store_brand.py — do not edit by hand.
##
## Holds the display name of the ONE store this build ships to. Generated rather than
## selected at runtime so a competitor's name is absent from the APK entirely, not just
## unused: naming a rival store inside a build is grounds for rejection (LESSONS L69).
##
## Current build: none

const EN := "the app store"
const FA := "فروشگاه برنامه"


func name_for_locale() -> String:
	return FA if I18n.locale == "fa" else EN
