#!/usr/bin/env python3
"""Generate `scripts/store_brand.gd` holding ONLY the target store's display name.

Keeping every store's name in `i18n.gd` puts all of them in every APK's string table,
even though a build ships to exactly one store — and a rival's name inside an APK is a
rejection (Myket, release 5.4). Selecting the name at build time means the other store's
name is not merely unused, it is *absent*.

    python3 gen_store_brand.py <game_dir> <store>     # store: bazaar | myket | none

The committed default is the neutral variant, so a desktop run, a test run, or a build
with no billing says "the app store" and names nobody.
"""
import os
import sys

BRANDS = {
    "bazaar": ("Cafe Bazaar", "کافه‌بازار"),
    "myket": ("Myket", "مایکت"),
    "none": ("the app store", "فروشگاه برنامه"),
    "": ("the app store", "فروشگاه برنامه"),
}

TEMPLATE = '''extends Node
## GENERATED by pipeline/gen_store_brand.py — do not edit by hand.
##
## Holds the display name of the ONE store this build ships to. Generated rather than
## selected at runtime so a competitor's name is absent from the APK entirely, not just
## unused: naming a rival store inside a build is grounds for rejection (LESSONS L69).
##
## Current build: {store}

const EN := "{en}"
const FA := "{fa}"


func name_for_locale() -> String:
	return FA if I18n.locale == "fa" else EN
'''


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    game_dir, store = sys.argv[1], sys.argv[2].strip().lower()
    if store not in BRANDS:
        print(f"unknown store '{store}' (known: {', '.join(k for k in BRANDS if k)})")
        return 1
    en, fa = BRANDS[store]
    path = os.path.join(game_dir, "scripts", "store_brand.gd")
    body = TEMPLATE.format(store=store or "none", en=en, fa=fa)
    previous = ""
    if os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            previous = fh.read()
    if previous == body:
        print(f"   store brand already '{store or 'none'}'")
        return 0
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(body)
    print(f"   store brand -> {store or 'none'} ({fa})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
